name: Deploy PHP App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Archive code
      run: zip -r deploy.zip . -x ".git/*"

    - name: Upload and deploy to EC2
      run: |
        # Copy zip to EC2
        scp -o StrictHostKeyChecking=no deploy.zip ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

        # SSH into EC2 and deploy
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          # Stop Apache (optional if needed)
          sudo systemctl stop httpd

          # Move zip to web root and extract
          sudo unzip -o /home/ec2-user/deploy.zip -d /var/www/html/
          # Set permissions
          sudo chown -R apache:apache /var/www/html
          sudo find /var/www/html -type d -exec chmod 755 {} \;
          sudo find /var/www/html -type f -exec chmod 644 {} \;

          # Start Apache
          sudo systemctl start httpd
        EOF
