name: CI/CD - PHP App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment via SSM
        uses: aws-actions/aws-cli@v2
        with:
          aws-region: eu-central-1
          args: |
            aws ssm send-command \
              --targets "Key=instanceIds,Values=i-06cf62b5137149cba" \
              --document-name "AWS-RunShellScript" \
              --comment "Deploy latest PHP app from GitHub" \
              --parameters 'commands=[
                "cd /var/www/html",
                "if [ -d .git ]; then git reset --hard && git pull origin main; else git clone https://github.com/beunblog/website.git .; fi",
                "sudo systemctl restart httpd"
              ]' \
              --region eu-central-1
