name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip project
        run: |
          zip -r deploy.zip . -x ".git/*"

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp deploy.zip s3://beunblogbucket/deploy-${GITHUB_SHA}.zip

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Trigger deploy on EC2 via SSM
        uses: aws-actions/aws-cli@v2
        with:
          aws-region: eu-central-1
          args: |
            ssm send-command \
              --targets "Key=instanceIds,Values=<YOUR_EC2_INSTANCE_ID>" \
              --document-name "AWS-RunShellScript" \
              --comment "Trigger deployment" \
              --parameters 'commands=["/home/ec2-user/deploy.sh"]'
