name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip project
        run: |
          zip -r deploy.zip . -x ".git/*"

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp deploy.zip s3://beunblogbucket/deploy-${GITHUB_SHA}.zip

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
  
      - name: Trigger deploy on EC2 via SSM
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=i-06cf62b5137149cba" \
            --document-name "AWS-RunShellScript" \
            --comment "Trigger deployment" \
            --parameters 'commands=[
                    "cd /var/www/html",
                    "aws s3 cp s3://beunblogbucket/deploy-'${GITHUB_SHA}'.zip ./deploy.zip",
                    "unzip -o deploy.zip",
                    "rm deploy.zip",
                    "sudo chown -R apache:apache /var/www/html",
                    "sudo chmod -R 755 /var/www/html",
                    "sudo systemctl restart httpd"
              ]'
              
