name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*"

    - name: Upload package to S3
      run: | 
        aws s3 cp deploy.zip s3://elasticbeanstalk-eu-central-1-417371241619/deploy-${GITHUB_SHA}.zip --acl bucket-owner-full-control

    - name: Verify upload
      run: aws s3 ls s3://elasticbeanstalk-eu-central-1-417371241619/deploy-${GITHUB_SHA}.zip
      
    - name: Create Application Version in EB
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name beunblog_website \
        --version-label $GITHUB_SHA \
        --source-bundle S3Bucket="elasticbeanstalk-eu-central-1-417371241619",S3Key="deploy-${GITHUB_SHA}.zip"

    - name: Wait for EB Environment to be Ready
      run: |
        while true; do
          STATE=$(aws elasticbeanstalk describe-environments \
            --environment-names bb-env \
            --query "Environments[0].Status" \
            --output text)
          echo "Current environment status: $STATE"
          if [ "$STATE" = "Ready" ]; then
            break
          fi
          echo "Waiting 10s..."
          sleep 10
        done

    - name: Update EB Environment to new version
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name bb-env \
          --version-label $GITHUB_SHA

