name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip project
        run: |
          zip -r deploy.zip . -x ".git/*"

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp deploy.zip s3://beunblogbucket/deploy-${GITHUB_SHA}.zip

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Trigger deploy on EC2
        run: |
          # Replace with your EC2 public IP or DNS
          EC2_PUBLIC_IP=ec2-3-122-224-4.eu-central-1.compute.amazonaws.com

          # Download and deploy on EC2 using SSH
          ssh -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP << 'EOF'
            # Navigate to your web root (e.g., /var/www/html)
            cd /var/www/html

            # Pull latest zip from S3
            aws s3 cp s3://beunblogbucket/deploy-${GITHUB_SHA}.zip ./deploy.zip

            # Unzip to web root
            unzip -o deploy.zip
            rm deploy.zip

            # Optional: restart Apache or PHP-FPM
            sudo systemctl restart httpd
          EOF
